### ISSUE TITLE
Deprecation warning for moment js

### ISSUE THREAD

**Issue by easternbloc** [UKHomeOffice/passports-template-mixins#27]
Run the tests and you'll get this deprecation warning.

```Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.```

**Comment by lennym** [comment]
Yes, it's this line here - https://github.com/UKHomeOffice/passports-template-mixins/blob/master/test/spec.index.js#L372 that causes that warning on account of instantiating a date with a non-ISO8601 string.

Fortunately:

* moment have said it will only be removed in a major version, and so since we don't allow major version updates in our package.json it won't stop working without noticing.
* if it does get removed then this test will start to fail
* the warning is triggered if the implementer passes a non-ISO string into the mixin, which is appropriate. The only way to suppress the warning would be to disallow it completely and throw an error, which I don't think is better.
